### ISSUE TITLE
無法用Rscript執行R

### ISSUE THREAD

**Issue by bobntu426** [rlads2021/hw2#20]
![image](https://user-images.githubusercontent.com/80089775/110442243-9d570200-80f5-11eb-87f2-543fd6eba73a.png)
請問我想執行R的時候為甚麼跳出這個而無法執行

**Comment by liao961120** [comment]
那你用 RStudio 打開 `index.Rmd` 然後按 "Knit" 看看能不能輸出：

![](https://user-images.githubusercontent.com/32927002/110242789-8c41b000-7f92-11eb-8a94-d9df9469b427.png)

**Comment by bobntu426** [comment]
![image](https://user-images.githubusercontent.com/80089775/110445549-32a7c580-80f9-11eb-829e-99b3d9fd3c81.png)
我後來把路徑設定好了，但是卻顯示找不到，是因為路徑有中文嗎，那要怎麼更改路徑?
