### ISSUE TITLE
如何在mac終端機用R

### ISSUE THREAD

**Issue by patricia40719** [rlads2021/hw2#4]
根據助教上面貼的這篇文，請問是要在mac終端機裡面輸入
```
/usr/bin/R
/usr/local/bin/R
/opt/local/bin/R
```
把以上三個輪流輸入終端機試試看嗎？
如果成功的話終端機應該顯示出什麼？
請問如果我在終端機中輸入Ｒ時，終端機顯示下列資訊
```
zhongpeijia@Peichia-macbook ~ % R
zsh: command not found: R
```
這是我上一堂課Ｒ下載失敗的意思嗎？

**Comment by liao961120** [comment]
可以參考上一則 Issue 的[說明](https://github.com/rlads2021/hw2/issues/3#issuecomment-791044583)喔
