### ISSUE TITLE
找不到Ｒ的路徑

### ISSUE THREAD

**Issue by patricia40719** [rlads2021/hw2#5]
雖然我在Rstudio的Console內輸入1+1後，有成功出現[1] 2，但是在Rstudio的Console輸入system("type R"}後，出現以下資訊
```
> system("type R")
sh: line 0: type: R: not found
```
出現了「R not fond」，沒有出現R的路徑，請問這樣該怎麼做？
還有請問家目錄是什麼？哪裡可以找到家目錄？謝謝助教

**Comment by liao961120** [comment]
我在 [Issue#3](https://github.com/rlads2021/hw2/issues/3) 裡面回覆囉，可以參考看看

BTW，相同主題的討論可以直接在原本的 Issue 3 下方進行，不須另開一個 Issue (這樣其他人遇到類似的問題也可以當作參考)
